### ISSUE TITLE
This file is not a pack?

### ISSUE THREAD

**Issue by carmparm** [jasongrier/sl#1]
Ableton for some reason isn't letting me install these packs. Keeps saying they are not pack files. Files are unzipped. :/

**Comment by rogerorange** [comment]
yes, i tried too - seems something went very wrong at the upload ... by the way: have been reading the article about hem at ableton.com - great work!

**Comment by aideendoran** [comment]
I too haven't been able to install these as a pack, could it be a compatibility issue?

**Comment by rogerorange** [comment]
I don't think its a compatibility issue - all files inside of the "Packs" folder have the same size (tiny 133 Bytes ...), so i came to the conclusion that it could be a problem related to the files themselves.

**Comment by berdovicj** [comment]
Same here

**Comment by phrolov** [comment]
These files are stored in Git Large File Storage, so you need to install git-lfs on your computer and clone the repo. BUT there is an error when I try to do this:

`Error downloading object: Devices/Seurat MIDI.alp (7b40151): Smudge error: Error downloading Devices/Seurat MIDI.alp (7b401511428bcdf739a5ac4cced9b77182537be247f912c1091ba134334b9fe5): batch response: This repository is over its data quota. Purchase more data packs to restore access.`

**Comment by James-William-Laird** [comment]
Do not waste your time with this, please. I doubt that this a user issue, although I might just be presumptuous.

**Comment by James-William-Laird** [comment]
Go back to Ableton (https://www.ableton.com/en/blog/jason-grier-demonstration-disc/?sc_src=email_2236657&sc_lid=132669068&sc_uid=1jtiQV8qew&sc_llid=295&sc_eh=1e58e63a3455b4a91) and redirect to HEM (http://hem.rocks/sound-library)... Originally I was brought here (GitHub) but now it is transferring me to WeTransfer (https://wetransfer.com/downloads/504f8a390c74aebf87d2825cdcce814a20171004193759/c16a0c1c8b5076b4949f4a968d05e51020171004193759/1f9cc3). I recommend all of you try this last link. I have know clue why all of this happened, but thanks anyway and good luck to those of you facing the previous issues listed here.

**Comment by carmparm** [comment]
Thanks for the follow up James!

**Comment by bernhard22** [comment]
I could download the als - files, but all the wav files are missing. Where can I download them?
Tanx a lot!!!

**Comment by tuhpawarez** [comment]
Sorry to say that the wetransfer link is gone. I just need the Seurat MIDI.alp for a project with lotsa voices. Would be very nice nice if someone who got a working copy could post it here.

thx
tuh pa warez

**Comment by jasongrier** [comment]
Hi everybody!

**All materials can be downloaded from my website:**

http://hem.rocks/

Thanks and sorry for the inconvenience!

J
