### ISSUE TITLE
Process Results: Clone a Repository

### ISSUE THREAD

**Issue by James-William-Laird** [jasongrier/sl#2]
Cloning into 'D:\Downloads\sl'...
remote: Counting objects: 369, done.        
remote: Compressing objects:  33% (1/3)           
remote: Compressing objects:  66% (2/3)           
remote: Compressing objects: 100% (3/3)           
remote: Compressing objects: 100% (3/3), done.        
Receiving objects:   0% (1/369)   
Receiving objects:   1% (4/369)   
Receiving objects:   2% (8/369)   
Receiving objects:   3% (12/369)   
Receiving objects:   4% (15/369)   
Receiving objects:   5% (19/369)   
Receiving objects:   6% (23/369)   
Receiving objects:   7% (26/369)   
Receiving objects:   8% (30/369)   
Receiving objects:   8% (33/369), 1.95 MiB | 1.90 MiB/s   
Receiving objects:   9% (34/369), 1.95 MiB | 1.90 MiB/s   
Receiving objects:   9% (35/369), 4.31 MiB | 2.11 MiB/s   
Receiving objects:   9% (35/369), 5.93 MiB | 1.94 MiB/s   
Receiving objects:   9% (35/369), 7.34 MiB | 1.81 MiB/s   
Receiving objects:   9% (35/369), 9.15 MiB | 1.81 MiB/s   
Receiving objects:   9% (35/369), 10.35 MiB | 1.58 MiB/s   
Receiving objects:   9% (35/369), 11.84 MiB | 1.45 MiB/s   
Receiving objects:   9% (35/369), 12.86 MiB | 1.39 MiB/s   
Receiving objects:  10% (37/369), 12.86 MiB | 1.39 MiB/s   
Receiving objects:  11% (41/369), 12.86 MiB | 1.39 MiB/s   
Receiving objects:  12% (45/369), 12.86 MiB | 1.39 MiB/s   
Receiving objects:  13% (48/369), 12.86 MiB | 1.39 MiB/s   
Receiving objects:  14% (52/369), 12.86 MiB | 1.39 MiB/s   
Receiving objects:  15% (56/369), 12.86 MiB | 1.39 MiB/s   
Receiving objects:  16% (60/369), 12.86 MiB | 1.39 MiB/s   
Receiving objects:  17% (63/369), 12.86 MiB | 1.39 MiB/s   
Receiving objects:  18% (67/369), 12.86 MiB | 1.39 MiB/s   
Receiving objects:  19% (71/369), 12.86 MiB | 1.39 MiB/s   
Receiving objects:  20% (74/369), 12.86 MiB | 1.39 MiB/s   
Receiving objects:  21% (78/369), 12.86 MiB | 1.39 MiB/s   
Receiving objects:  22% (82/369), 12.86 MiB | 1.39 MiB/s   
Receiving objects:  23% (85/369), 12.86 MiB | 1.39 MiB/s   
Receiving objects:  24% (89/369), 12.86 MiB | 1.39 MiB/s   
Receiving objects:  25% (93/369), 12.86 MiB | 1.39 MiB/s   
Receiving objects:  26% (96/369), 12.86 MiB | 1.39 MiB/s   
Receiving objects:  27% (100/369), 12.86 MiB | 1.39 MiB/s   
Receiving objects:  28% (104/369), 12.86 MiB | 1.39 MiB/s   
Receiving objects:  29% (108/369), 12.86 MiB | 1.39 MiB/s   
Receiving objects:  30% (111/369), 12.86 MiB | 1.39 MiB/s   
Receiving objects:  31% (115/369), 12.86 MiB | 1.39 MiB/s   
Receiving objects:  32% (119/369), 12.86 MiB | 1.39 MiB/s   
Receiving objects:  33% (122/369), 12.86 MiB | 1.39 MiB/s   
Receiving objects:  34% (126/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  35% (130/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  36% (133/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  37% (137/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  38% (141/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  39% (144/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  40% (148/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  41% (152/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  42% (155/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  43% (159/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  44% (163/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  45% (167/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  46% (170/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  47% (174/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  48% (178/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  49% (181/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  50% (185/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  51% (189/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  52% (192/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  53% (196/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  54% (200/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  55% (203/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  56% (207/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  57% (211/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  58% (215/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  59% (218/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  60% (222/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  61% (226/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  62% (229/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  63% (233/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  64% (237/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  65% (240/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  66% (244/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  67% (248/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  68% (251/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  69% (255/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  70% (259/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  71% (262/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  72% (266/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  73% (270/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  74% (274/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  75% (277/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  76% (281/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  77% (285/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  78% (288/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  79% (292/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  80% (296/369), 13.79 MiB | 1.41 MiB/s   
Receiving objects:  80% (297/369), 15.03 MiB | 1.44 MiB/s   
Receiving objects:  80% (297/369), 16.67 MiB | 1.53 MiB/s   
Receiving objects:  80% (297/369), 17.57 MiB | 1.40 MiB/s   
Receiving objects:  80% (297/369), 19.51 MiB | 1.55 MiB/s   
Receiving objects:  80% (298/369), 20.52 MiB | 1.69 MiB/s   
Receiving objects:  80% (298/369), 23.96 MiB | 1.74 MiB/s   
Receiving objects:  80% (298/369), 26.54 MiB | 2.04 MiB/s   
Receiving objects:  81% (299/369), 26.54 MiB | 2.04 MiB/s   
Receiving objects:  81% (299/369), 29.04 MiB | 2.32 MiB/s   
Receiving objects:  81% (299/369), 31.86 MiB | 2.46 MiB/s   
Receiving objects:  81% (300/369), 33.32 MiB | 2.56 MiB/s   
Receiving objects:  82% (303/369), 34.51 MiB | 2.56 MiB/s   
Receiving objects:  83% (307/369), 34.51 MiB | 2.56 MiB/s   
Receiving objects:  84% (310/369), 34.51 MiB | 2.56 MiB/s   
Receiving objects:  85% (314/369), 34.51 MiB | 2.56 MiB/s   
Receiving objects:  86% (318/369), 34.51 MiB | 2.56 MiB/s   
Receiving objects:  87% (322/369), 34.51 MiB | 2.56 MiB/s   
Receiving objects:  88% (325/369), 34.51 MiB | 2.56 MiB/s   
Receiving objects:  89% (329/369), 34.51 MiB | 2.56 MiB/s   
Receiving objects:  90% (333/369), 34.51 MiB | 2.56 MiB/s   
Receiving objects:  91% (336/369), 34.51 MiB | 2.56 MiB/s   
Receiving objects:  92% (340/369), 34.51 MiB | 2.56 MiB/s   
Receiving objects:  93% (344/369), 34.51 MiB | 2.56 MiB/s   
Receiving objects:  94% (347/369), 34.51 MiB | 2.56 MiB/s   
Receiving objects:  94% (350/369), 37.22 MiB | 2.62 MiB/s   
Receiving objects:  94% (350/369), 39.82 MiB | 2.67 MiB/s   
Receiving objects:  94% (350/369), 42.21 MiB | 2.59 MiB/s   
Receiving objects:  94% (350/369), 43.81 MiB | 2.30 MiB/s   
Receiving objects:  94% (350/369), 45.80 MiB | 2.18 MiB/s   
Receiving objects:  94% (350/369), 48.28 MiB | 2.15 MiB/s   
Receiving objects:  95% (351/369), 48.76 MiB | 1.97 MiB/s   
Receiving objects:  96% (355/369), 48.76 MiB | 1.97 MiB/s   
Receiving objects:  97% (358/369), 48.76 MiB | 1.97 MiB/s   
Receiving objects:  98% (362/369), 48.76 MiB | 1.97 MiB/s   
remote: Total 369 (delta 0), reused 1 (delta 0), pack-reused 366        
Receiving objects:  99% (366/369), 48.76 MiB | 1.97 MiB/s   
Receiving objects: 100% (369/369), 48.76 MiB | 1.97 MiB/s   
Receiving objects: 100% (369/369), 49.17 MiB | 1.96 MiB/s, done.
Resolving deltas:   0% (0/81)   
Resolving deltas:   3% (3/81)   
Resolving deltas:   4% (4/81)   
Resolving deltas:   6% (5/81)   
Resolving deltas:   8% (7/81)   
Resolving deltas:   9% (8/81)   
Resolving deltas:  11% (9/81)   
Resolving deltas:  16% (13/81)   
Resolving deltas:  19% (16/81)   
Resolving deltas:  44% (36/81)   
Resolving deltas:  56% (46/81)   
Resolving deltas:  60% (49/81)   
Resolving deltas:  62% (51/81)   
Resolving deltas:  66% (54/81)   
Resolving deltas:  80% (65/81)   
Resolving deltas: 100% (81/81)   
Resolving deltas: 100% (81/81), done.
batch response: This repository is over its data quota. Purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/jasongrier/sl.git/info/lfs'

sl/Demonstration Disc (.MD) file is available to open with Microsoft's WordPad Application
sl/Devices (.MD) file is unavailable to open
sl/Devices Seurat MIDI.alp is 1KB and is invalid within Ableton Live 9
sl/Misc (.jpgs) are available, there are 4 files
Packs/Acoustic Guitar (.alp) is 1 KB and is invalid
Packs/Acoustic Guitar (.MD) is available

All subsequent files repeat unavailability of (.MD) files and (.alp) files are invalid...
Except that the sl/Tutorial (.MD) and (.als) files are of normal sizes (88 KB, 503 KB, etc.)

.gitattributes is 1 KB
.gitignore is 1 KB
LICENSE is working and is available through Notepad
README is working
Swatches is 1 KB and is invalid

This is my first introduction to GitHub, and to say the least, it has been frustrating. I enjoyed the interview and support the intention behind this style of release, but I disagree with the outlet for sharing of the files. This process is identical regardless if I use the GitHub desktop application or download the (.zip) and extract the files.

Please either enlighten me as to what I am doing wrong or fix the issues with the download portal/files themselves. Or submit a request Ableton to stop promoting this release, remove the notices, and stop emailing people until this is ready.

I am sorry to be so gruff, but I have wasted 3 hours trying to assess what to do about this. The capacity for interest that engaged me in the detail that you put into this has inverted and is turning into disdain.

Thanks,
-James

**Comment by dantheawesomebam** [comment]
Same here, not so gruff though, only spent one hour so far :D :D

**Comment by jasongrier** [comment]
Hi everybody!

**All materials can be downloaded from my website:**

http://hem.rocks/

Thanks and sorry for the inconvenience!

J
